const Language = {
  all: '全体',
  login: 'ログイン',
  login_success: 'ログイン成功',
  login_success_message: 'ログインに成功しました。',
  login_fail: 'ログイン失敗',
  logout: 'ログアウト',
  logout_message: 'ログアウトしますか？',
  logout_fail: 'ログアウトに失敗しました。',
  enter: '確認',
  next_step: '次へ',
  complete: '完了',
  cancel: 'キャンセル',
  fail: '失敗',
  error: 'エラー',
  prev: '戻る',
  list_empty_title: 'データなし',
  list_empty_comment: '登録されたデータがありません。',
  search: '検索',
  search_result: '検索結果',
  input_keyword: '検索キーワードを入力してください。',
  search_list_empty_title: '検索結果がありません。',
  search_list_empty_comment: '検索語を変更して再度検索してください。',
  topic: 'トピック',
  company_info: '企業情報',
  post_add: 'ポスト作成',
  best_topic: 'ベストトピック',
  topic_list: 'トピックリスト',
  bookmark: 'ブックマーク',
  my_topic: 'マイトピック',
  my_page: 'マイページ',
  mobile_login_code_title: 'モバイル端末の認証コード確認',
  mobile_login_code_message:
    'Tomodomoモバイルアプリの「マイページ→Webからログイン」メニューで表示された\n認証コードを確認し入力してください。',
  certification_code: '認証コード',
  network_timeout:
    '接続時間が超過しました。\nネットワークの状態を確認してください。',
  network_error_title: 'ネットワーク連結不可',
  login_after_title: 'ログインしてください。',
  login_after_message: 'ログイン後、アプリがご利用できます。',
  join_message:
    'まだTomodomoの会員ではないですか？\n簡単な無料会員登録でご利用できます。(１分)',
  order_new: '最新順',
  order_old: '古い順',
  order_recommend: '推薦順',
  order_point_high: '高い評価順',
  order_point_low: '低い評価順',
  order_written_working: '在籍中作成',
  order_written_after: '転職後作成',
  select: '選択',
  comment: 'コメント',
  comment_write: 'コメント作成',
  loading: '読み込み中',
  loading_comment: 'データを読み込んでいます。',
  no_data: 'データがありません。',
  no_post: 'ポストがありません。',
  no_post_message: '登録されたポストがありません',
  no_comment: '登録されたコメントがありません。',
  no_comment_message: 'コメントを入力してください。',
  add_comment: 'コメント作成',
  add_comment_cancel: 'コメント作成キャンセル',
  edit_comment: 'コメント変更',
  to_comment: 'へのコメント',
  input_comment: 'コメント入力',
  register_post_success_title: 'ポスト作成完了',
  register_post_success_message: 'ポストを登録しました。',
  edit: '修正',
  edit_post: 'ポスト修正',
  edit_post_title: 'ポストを修正しました。',
  edit_post_message: 'ポストを修正してもよろしいでしょうか？',
  delete: '削除',
  register: '登録',
  input_title: 'タイトルを３桁以上入力してください。',
  input_post_contents:
    '内容を入力します。\nイメージを添付するには、下のカメラまたは写真ボタンをタッチしてください。',
  register_post_message: 'ポストを登録しますか？',
  edit_post_success: '修正完了',
  edit_post_success_message: 'ポストが修正されました。',
  delete_post_success: '削除完了',
  delete_post_success_message: 'ポストが削除されました。',
  edit_reply_success: '修正完了',
  edit_reply_success_message: 'コメントが修正されました。',
  delete_reply_success: '削除完了',
  delete_reply_success_message: 'コメントが削除されました。',
  report: '通報',
  input_report_reason: '申告理由を入力してください。',
  report_success_title: '申告完了',
  report_success_message: '申告が登録しました。',
  company_search_title: '在籍社員による会社レビュー',
  company_search_message: '在籍社員による給料の情報、福利厚生を確認できます！',
  company_banner_title: '在籍している会社メールを利用して認証してください。',
  company_banner_message:
    'モバイルアプリで認証したら会社レビューを閲覧できます。',
  my_company_banner_title: '私の会社レビュー',
  my_company_banner_message:
    '社員のレビューは就活者や転職者が会社を検討するときに役立ちます。',
  input_search_company: '検索する会社名を入力してください。',
  request_new_company:
    '探す会社がない場合には、知りたい会社を直接指定してください。',
  company_list: '企業リスト',
  popular_company: '話題の企業順位',
  my_company_review: '私の会社レビュー',
  request_new_company_title: '企業登録申請',
  request_new_company_message:
    '知りたい企業名/企業のメールを入力してください。',
  input_company_name: '企業名を入力してください。',
  input_company_email:
    '在籍している会社のメールを入力してください。例)XXX@tomodomo-net.com',
  invalid_email: 'メールアドレスの形式が間違っています。',
  request_new_company_result: '企業登録申請結果',
  search_company: '企業の検索',
  search_company_result: '企業の検索結果',
  company_view_annual: '年俸',
  company_board: 'ポスト',
  company_view_review: 'レビューを見る',
  write_review: 'レビュー作成',
  register_review: 'レビュー登録',
  register_review_select: 'レビュー作成企業選択',
  company_review_status_ready: '承認待機',
  company_review_status_fail: '承認拒否',
  company_review_status_success: '承認済み',
  delete_review_title: 'レビュー作成を中止しますか？',
  delete_review_message:
    '作成途中で中止すると作成したレビューは保存されなくなります。',
  delete_review: 'レビュー削除',
  company_review_blur_message:
    '全体レビューを見るためには企業メールで認証(1分)をしてください。',
  company_review_blur_message_register:
    '全体レビューを見るためにはレビューを作成してください。',
  company_review_blur_message_wait:
    'レビューが承認されたら、すべてのレビューを確認できます。',
  company_point_register: '☆評価',
  company_point_career: 'キャリアアップ',
  company_point_head: '経営陣',
  company_point_culture: '企業文化',
  company_point_balance: 'ワーク・ライフ・バランス',
  company_point_pay: '給料・福利厚生',
  company_name: '企業名',
  homepage: 'ホームページ',
  address: 'アドレス',
  founding_date: '設立年月日',
  worker_count: '従業員数',
  head_office: '本社',
  business_type: '業種',
  company_topic: '関連トピック',
  simple_comment: '簡単なコメント',
  input_simple_comment: '簡単なコメントを入力してください。',
  advantage: '長所',
  input_advantage: '長所を入力してください。',
  disadvantage: '短所',
  resign_reason: '転職の理由',
  input_resign_reason: '転職の理由を入力してください。',
  input_disadvantage: '短所を入力してください。',
  review_comment_input_placeholder:
    '簡単なコメントを5~30文字で書いてください。',
  review_advantage_input_placeholder: '長所を30~150文字以上書いてください。',
  review_disadvantage_input_placeholder: '短所を30~150文字以上書いてください。',
  review_resign_reason_input_placeholder:
    '転職の理由を30~400文字以上書いてください。',
  review_location_input_placeholder: '勤務地域を2~20文字以上書いてください。',
  work_information: '在籍情報',
  work_status: '在籍状態',
  work_location: '勤務地域',
  work_start: '勤務開始',
  work_end: '勤務終了',
  status_employee: '在籍中',
  status_retire: '退職',
  job: '業種',
  company_review_error_year_message:
    '勤務終了日が勤務開始日より前になっています。',
  review_register_success_title: 'レビュー作成完了',
  review_register_success_message: 'レビュー作成を完了しました。',
  company_recommend_message: 'は働きたい企業ですか？',
  company_intro: '企業紹介',
  intro: '紹介',
  review: 'レビュー',
  company_review: '企業のレビュー',
  board: 'ポスト',
  annual_salary: '年俸',
  news: 'ニュース',
  input_search_company_post:
    '@企業名：この企業と関連あるポストが検索できます。',
  recommend_keyword: '推薦キーワード',
  post_for: 'のポスト',
  annual_for: 'の年俸情報',
  annual_job_group_comment: 'の年俸情報を職種別で確認してください。',
  select_job_group: '職種を選んでください。',
  average: '平均',
  max: '最大',
  min: '最小',
  money_unit: '円',
  news_link: 'ニュースリンク',
  company_tab_info: 'の紹介',
  company_tab_review: 'のレビュー',
  company_tab_board: 'の関連ポスト',
  company_tab_annual: 'の給料情報',
  company_tab_news: 'のニュース',
  company_tab_review_other: 'の他のレビュー',
  person_unit: '人',
  review_more_view: 'もっと見る',
  company_vote_message: 'は働きたい企業ですか？',
  company_vote_good_title: '推薦完了',
  company_vote_good_message: '企業を推薦しました。',
  company_vote_bad_title: '非推薦完了',
  company_vote_bad_message: '企業を非推薦しました。',
  not_found_title: 'ページが見つかりません。',
  not_fond_message: 'URLをご確認ください。',
  receive_post: 'ポストを作成しました。',
  receive_comment: 'ポストに「コメント」をいただきました。',
  receive_like: 'ポストに「いいね」をいただきました',
  receive_report: 'の理由で通報を受けつきました。',
  receive_report_pre: '承認された通報回数:',
  receive_report_after: '３回以上の通報を受けついたらご利用が制限されます。',
  helpful: '役に立った',
  share: '共有する',
  url_copy: 'URLコピー',
  url_copy_success_title: 'コピーされました。',
  url_copy_success_message: 'レビューのURLがコピーされました。',
  url_input_title: 'Link',
  url_input_placeholder: 'URLを入力してください。',
  url_input_error: 'URL形式が間違いました。',
  unavailable_words: '登録できない単語があります。',
  select_company: '企業を選択してください。',
  certification_title: 'TOMODOMO自動認証',
  certification_message:
    'ポップアップが表示されない場合は、下のボタンをタップしてください。',
  certification_confirm: '直接認証する',
  certification_go_mobile: 'モバイルから接続してください。',
};

export default Language;
